import {offerService} from '../offers.mjs';
import {test} from 'node:test';import assert from 'node:assert/strict';import {createTenantStore} from '../tenant-store.mjs';import {quoteService,validateQuote,matchCarriers} from '../quotes.mjs';import {portalOperations} from '../operations.mjs';
const request={company:'Müşteri A',person:'Test Yetkili',email:'customer@example.com',phone:'5550000000',direction:'İthalat',mode:'Kara',originCountry:'Almanya',originCity:'Berlin',originAddress:'Yükleme adresi',destinationCountry:'Türkiye',destinationCity:'İstanbul',destinationAddress:'Teslim adresi',goods:'Makine parçası',packages:'2',gross:'120',net:'100',volume:'2',dimensions:'100 x 100 x 100 cm',readyDate:'2026-10-01',incoterm:'FCA'};
const carrier=(id,mode,email)=>({id,name:id,isCarrier:true,serviceCountries:['Almanya'],contacts:[{first:'Test',transportMode:mode,email}]});
test('quote fields are mandatory and invalid weights cannot create drafts',()=>{for(const key of Object.keys(request))assert.throws(()=>validateQuote({...request,[key]:''}));assert.throws(()=>validateQuote({...request,net:'200'}));assert.equal(matchCarriers([carrier('a','Hava','a@example.com')],request).length,0);});
test('each matching carrier gets an isolated reviewed draft, no match is actionable',async()=>{const store=await createTenantStore();try{const token=store.login('yonetici.demo','AscendDemo!2026').token,admin=store.principal({headers:{cookie:'ascend_sid='+token}});await store.sync(admin,{_revision:store.revision(),companies:[carrier('a','Kara','a@example.com'),carrier('b','Kara','b@example.com'),carrier('c','Hava','c@example.com')]});const quotes=quoteService(store);const result=quotes.create(admin,request);assert.equal(result.carrierCount,2);const row=quotes.list(admin)[0];assert.deepEqual(row.drafts.map(d=>d.body.to[0]).sort(),['a@example.com','b@example.com']);assert.ok(row.drafts.every(d=>!d.body.text.includes('customer@example.com')));assert.equal(portalOperations(store).outbox(admin).length,0);assert.throws(()=>quotes.approve({...admin,role:'Operasyon'},{id:row.drafts[0].id,reviewed:true,subject:'A',text:'B'}),e=>e.status===403);quotes.approve(admin,{id:row.drafts[0].id,reviewed:true,subject:'Fiyat talebi',text:row.drafts[0].body.text});assert.equal(portalOperations(store).outbox(admin).length,1);assert.equal(quotes.create(admin,{...request,originCountry:'Japonya'}).status,'needs-carrier');}finally{store.close();}});

test('offers enforce admin access, revisions and reviewed idempotent mail',async()=>{const store=await createTenantStore();try{const token=store.login('yonetici.demo','AscendDemo!2026').token,u=store.principal({headers:{cookie:'ascend_sid='+token}});await store.sync(u,{companies:[carrier('a','Kara','a@example.com')]});const q=quoteService(store).create(u,request),svc=offerService(store);assert.throws(()=>svc.list({...u,role:'Operasyon'}),e=>e.status===403);assert.throws(()=>svc.list({...u,role:'Müşteri'}),e=>e.status===403);const body={quoteId:q.id,carrierId:'a',purchase:'100.25',sale:'150',currency:'EUR',validUntil:'2026-10-01',status:'Teklif geldi'};assert.throws(()=>svc.save(u,{...body,purchase:'1.234'}));const saved=svc.save(u,body);assert.equal(svc.list(u)[0].body.purchase,100.25);assert.throws(()=>svc.save(u,{...body,id:saved.id,version:0}),e=>e.status===409);const mail={...saved,to:'customer@example.com',subject:'Teklif',text:'Navlun 150 EUR'};assert.throws(()=>svc.send(u,mail));svc.send(u,{...mail,reviewed:true});svc.send(u,{...mail,reviewed:true});assert.equal(portalOperations(store).outbox(u).length,1);assert.equal(svc.list(u)[0].mail.status,'waiting-provider');}finally{store.close();}});

test('incoming carrier price can be saved before customer price exists',async()=>{const store=await createTenantStore();try{const token=store.login('yonetici.demo','AscendDemo!2026').token,u=store.principal({headers:{cookie:'ascend_sid='+token}});await store.sync(u,{companies:[carrier('a','Kara','a@example.com')]});const q=quoteService(store).create(u,request),svc=offerService(store);const saved=svc.save(u,{quoteId:q.id,carrierId:'a',purchase:'100',sale:'',currency:'EUR',validUntil:'2026-10-01',status:'Teklif geldi'});assert.equal(svc.list(u)[0].body.sale,null);assert.throws(()=>svc.send(u,{...saved,reviewed:true,to:'customer@example.com',subject:'Test',text:'Test'}));}finally{store.close();}});
