import {DatabaseSync,backup} from 'node:sqlite';
import {mkdir,readFile,copyFile} from 'node:fs/promises';
import {dirname,join,basename} from 'node:path';
export async function openPortalDatabase(legacyPath){
 const path=legacyPath?legacyPath.replace(/\.json$/i,'')+'.sqlite':':memory:';
 if(legacyPath)await mkdir(dirname(path),{recursive:true});
 const db=new DatabaseSync(path);db.exec('PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000; CREATE TABLE IF NOT EXISTS state(id INTEGER PRIMARY KEY CHECK(id=1),revision INTEGER NOT NULL,body TEXT NOT NULL); CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY, at TEXT NOT NULL, actor TEXT NOT NULL, action TEXT NOT NULL, detail TEXT NOT NULL); CREATE TABLE IF NOT EXISTS documents(id TEXT PRIMARY KEY,module TEXT NOT NULL,record_id TEXT NOT NULL,name TEXT NOT NULL,version INTEGER NOT NULL,visible INTEGER NOT NULL,mime TEXT NOT NULL,sha256 TEXT NOT NULL,body BLOB NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL); CREATE TABLE IF NOT EXISTS outbox(id TEXT PRIMARY KEY,unique_key TEXT UNIQUE NOT NULL,status TEXT NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,next_at TEXT NOT NULL,payload TEXT NOT NULL,last_error TEXT); CREATE TABLE IF NOT EXISTS resets(token_hash TEXT PRIMARY KEY,username TEXT NOT NULL,expires INTEGER NOT NULL);');
 if(legacyPath&&!db.prepare('SELECT id FROM state WHERE id=1').get()){try{const old=JSON.parse(await readFile(legacyPath,'utf8'));db.prepare('INSERT INTO state VALUES(1,0,?)').run(JSON.stringify(old));await copyFile(legacyPath,legacyPath+'.pre-sqlite-backup');}catch(e){if(e.code!=='ENOENT')throw e;}}
 const current=()=>db.prepare('SELECT * FROM state WHERE id=1').get();
 function audit(actor,action,detail={}){db.prepare('INSERT INTO audit(at,actor,action,detail) VALUES(?,?,?,?)').run(new Date().toISOString(),actor,action,JSON.stringify(detail));}
 function save(state,expected,actor='system',changes={}){db.exec('BEGIN IMMEDIATE');try{const row=current();if(row&&expected!==row.revision)throw Object.assign(Error('Kayıt başka bir oturumda güncellendi. Sayfayı yenileyin.'),{status:409});const revision=(row?.revision??-1)+1;db.prepare('INSERT INTO state VALUES(1,?,?) ON CONFLICT(id) DO UPDATE SET revision=excluded.revision,body=excluded.body').run(revision,JSON.stringify(state));audit(actor,'state.update',changes);db.exec('COMMIT');return revision;}catch(e){db.exec('ROLLBACK');throw e;}}
 async function makeBackup(){if(!legacyPath)throw Error('Kalıcı veritabanı gerekli');const folder=join(dirname(path),'backups');await mkdir(folder,{recursive:true});const target=join(folder,basename(path)+'.'+new Date().toISOString().replace(/[:.]/g,'-')+'.sqlite');await backup(db,target);try{await copyFile(legacyPath+'.key',target+'.key');}catch(e){if(e.code!=='ENOENT')throw e;}const check=new DatabaseSync(target,{readOnly:true});try{if(check.prepare('PRAGMA integrity_check').get().integrity_check!=='ok')throw Error('Yedek doğrulanamadı');}finally{check.close();}return {file:basename(target),createdAt:new Date().toISOString()};}
 let timer;if(legacyPath){await makeBackup();timer=setInterval(()=>makeBackup().catch(()=>audit('system','backup.failed',{message:'Otomatik yedek oluşturulamadı'})),6*3600000);timer.unref();}
 return {db,current,save,audit,makeBackup,close(){clearInterval(timer);db.close();},path};
}
