import {simpleParser} from 'mailparser';
import mammoth from 'mammoth';
import ExcelJS from 'exceljs';
import {Readable} from 'node:stream';
import {getDocument} from 'pdfjs-dist/legacy/build/pdf.mjs';
export const fieldLabels={company:['Firma','Company'],person:['Yetkili','Contact person'],email:['E-posta','Email','E-mail'],phone:['Telefon','Phone'],direction:['İşlem yönü','Direction'],mode:['Taşıma türü','Transport mode','Mode'],originCountry:['Çıkış ülkesi','Origin country'],originCity:['Çıkış şehri','Origin city'],originAddress:['Yükleme adresi','Loading address'],destinationCountry:['Varış ülkesi','Destination country'],destinationCity:['Varış şehri','Destination city'],destinationAddress:['Teslim adresi','Delivery address'],goods:['Eşya','Eşya açıklaması','Goods','Commodity'],packages:['Toplam kap','Kap','Palet','Packages','Pallets'],gross:['Brüt kg','Brüt kilo','Gross weight','Gross'],net:['Net kg','Net kilo','Net weight','Net'],dimensions:['Ölçüler','Kap ölçüleri','Dimensions'],readyDate:['Eşyanın Hazır Olma Tarihi','Hazır tarihi','Ready date'],incoterm:['Teslim şekli','Incoterm'],purchase:['Navlun','Navlun alış','Freight','Price'],currency:['Döviz','Currency'],validUntil:['Geçerlilik','Valid until','Validity'],transit:['Transit süre','Transit time'],eta:['ETA','Tahmini varış tarihi'],costs:['Masraflar','Charges','Costs']};
const clean=s=>String(s||'').replace(/\r/g,'').replace(/[\u0000-\u0008]/g,'');
export function candidatesFrom(sources){const result={};for(const source of sources)for(const line of source.text.split('\n')){const m=line.match(/^\s*([^:\t]{1,70})\s*[:\t]\s*(.{1,2000})$/);if(!m)continue;const label=m[1].trim().toLocaleLowerCase('tr');for(const [key,labels] of Object.entries(fieldLabels))if(labels.some(x=>x.toLocaleLowerCase('tr')===label)){const item={value:m[2].trim(),source:source.name,evidence:line.slice(0,2200)};(result[key]??=[]).push(item);}}return result;}
function checkOfficeArchive(bytes){let total=0,count=0;for(let i=0;i+46<=bytes.length;i++){if(bytes.readUInt32LE(i)!==0x02014b50)continue;const size=bytes.readUInt32LE(i+24);if(size===0xffffffff)throw Error('ZIP64 desteklenmiyor');total+=size;count++;if(total>20*1024*1024||count>2000)throw Error('Açılmış belge boyutu sınırı');i+=45+bytes.readUInt16LE(i+28)+bytes.readUInt16LE(i+30)+bytes.readUInt16LE(i+32);}if(!count)throw Error('Office arşivi okunamadı');}
export async function extractMail(bytes){if(bytes.length>3*1024*1024)throw Error('EML dosyası en fazla 3 MB olabilir.');const mail=await simpleParser(bytes,{skipImageLinks:true,maxHtmlLengthToParse:200000});if(!mail.from&&!mail.subject&&!mail.text)throw Error('Geçerli bir EML okunamadı');const sources=[],attachments=[];let remaining=200000;const add=(name,text)=>{text=clean(text);const truncated=text.length>remaining;const retained=text.slice(0,remaining);remaining-=retained.length;if(retained.trim())sources.push({name,text:retained,truncated});return truncated;};add('Mail metni',mail.text||'');if((mail.attachments||[]).length>20)throw Error('Bir mailde en fazla 20 ek incelenebilir.');
 for(const a of mail.attachments||[]){const name=String(a.filename||'İsimsiz ek').slice(0,200),ext=name.split('.').pop().toLowerCase();const info={name,size:a.size,status:'unsupported',message:'Bu dosya türü otomatik okunmuyor.'};attachments.push(info);if(!remaining){info.status='limit';info.message='Metin sınırına ulaşıldı; bu ek incelenmedi.';continue;}try{
 if(['docx','xlsx'].includes(ext))checkOfficeArchive(a.content);
 if(ext==='pdf'){const task=getDocument({data:new Uint8Array(a.content),isEvalSupported:false,useSystemFonts:false,disableFontFace:true});let doc;try{doc=await task.promise;if(doc.numPages>30){info.status='limit';info.message='PDF 30 sayfadan fazla; incelenmedi.';continue;}let textCount=0,emptyPages=0;for(let n=1;n<=doc.numPages;n++){const page=await doc.getPage(n),content=await page.getTextContent();const text=content.items.map(i=>i.str+(i.hasEOL?'\n':' ')).join('');textCount+=text.trim().length;if(!text.trim())emptyPages++;add(name+' / Sayfa '+n,text);}info.status=textCount?(emptyPages?'partial':'read'):'ocr-required';info.message=textCount?'Yalnız metin katmanı çıkarıldı; görseller ve tablo düzeni elle kontrol edilmeli.'+(emptyPages?' '+emptyPages+' sayfada metin bulunamadı; OCR gerekli.':''):'Taranmış/görsel PDF: OCR bağlantısı gerekli.';}finally{await task.destroy();}}
 else if(ext==='docx'){const r=await mammoth.extractRawText({buffer:a.content});info.status=add(name,r.value)?'partial':'read';info.message=r.messages.length?'Metin okundu; belge uyarıları var, kaynağı kontrol edin.':'Metin çıkarıldı; belge içindeki görseller incelenmedi.';}
 else if(ext==='xlsx'){const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(a.content);let cells=0;for(const sheet of workbook.worksheets){const lines=[];sheet.eachRow(row=>{if(cells>20000)return;const values=[];row.eachCell({includeEmpty:true},cell=>{cells++;values.push(cell.text);});lines.push(values.join('\t'));});add(name+' / '+sheet.name,lines.join('\n'));}info.status=cells>20000?'partial':'read';info.message='Hücre metinleri okundu; formüller çalıştırılmadı, görsel ve grafikler incelenmedi.';}
 else if(ext==='csv'){const decoded=new TextDecoder('utf-8',{fatal:true}).decode(a.content);const workbook=new ExcelJS.Workbook();const sheet=await workbook.csv.read(Readable.from([decoded]));let rows=0;const lines=[];sheet.eachRow(row=>{if(++rows<=20000)lines.push(row.values.slice(1).map(v=>String(v??'')).join('\t'));});info.status=add(name,lines.join('\n'))||rows>20000?'partial':'read';info.message='CSV hücreleri okundu.';}
 else if(ext==='txt'){const text=new TextDecoder('utf-8',{fatal:true}).decode(a.content);info.status=add(name,text)?'partial':'read';info.message='UTF-8 metin okundu.';}
 else if(['png','jpg','jpeg','tif','tiff','webp'].includes(ext)){info.status='ocr-required';info.message='Görsel için OCR bağlantısı gerekli.';}
 }catch{info.status='unreadable';info.message='Şifreli, bozuk veya okunamayan ek; elle kontrol edin.';}}
 return {subject:clean(mail.subject).slice(0,500),from:mail.from?.text?.slice(0,500)||'',sources,attachments,candidates:candidatesFrom(sources),notice:'Otomatik çıkarım öneridir. Eksik/çelişkili alanları kaynak belgelerle kontrol edin. OCR ve dış yapay zekâ bağlantısı etkin değildir.'};
}
