/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DijitalCozumlerRouteImport } from './routes/dijital-cozumler'
import { Route as GlobalAgRouteImport } from './routes/global-ag'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as HizmetlerimizRouteImport } from './routes/hizmetlerimiz'
import { Route as IletisimRouteImport } from './routes/iletisim'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DijitalCozumlerRoute = DijitalCozumlerRouteImport.update({
  id: '/dijital-cozumler',
  path: '/dijital-cozumler',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalAgRoute = GlobalAgRouteImport.update({
  id: '/global-ag',
  path: '/global-ag',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const HizmetlerimizRoute = HizmetlerimizRouteImport.update({
  id: '/hizmetlerimiz',
  path: '/hizmetlerimiz',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dijital-cozumler': typeof DijitalCozumlerRoute
  '/global-ag': typeof GlobalAgRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hizmetlerimiz': typeof HizmetlerimizRoute
  '/iletisim': typeof IletisimRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dijital-cozumler': typeof DijitalCozumlerRoute
  '/global-ag': typeof GlobalAgRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hizmetlerimiz': typeof HizmetlerimizRoute
  '/iletisim': typeof IletisimRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dijital-cozumler': typeof DijitalCozumlerRoute
  '/global-ag': typeof GlobalAgRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hizmetlerimiz': typeof HizmetlerimizRoute
  '/iletisim': typeof IletisimRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dijital-cozumler'
    | '/global-ag'
    | '/hakkimizda'
    | '/hizmetlerimiz'
    | '/iletisim'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dijital-cozumler'
    | '/global-ag'
    | '/hakkimizda'
    | '/hizmetlerimiz'
    | '/iletisim'
  id:
    | '__root__'
    | '/'
    | '/dijital-cozumler'
    | '/global-ag'
    | '/hakkimizda'
    | '/hizmetlerimiz'
    | '/iletisim'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DijitalCozumlerRoute: typeof DijitalCozumlerRoute
  GlobalAgRoute: typeof GlobalAgRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  HizmetlerimizRoute: typeof HizmetlerimizRoute
  IletisimRoute: typeof IletisimRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dijital-cozumler': {
      id: '/dijital-cozumler'
      path: '/dijital-cozumler'
      fullPath: '/dijital-cozumler'
      preLoaderRoute: typeof DijitalCozumlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-ag': {
      id: '/global-ag'
      path: '/global-ag'
      fullPath: '/global-ag'
      preLoaderRoute: typeof GlobalAgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hizmetlerimiz': {
      id: '/hizmetlerimiz'
      path: '/hizmetlerimiz'
      fullPath: '/hizmetlerimiz'
      preLoaderRoute: typeof HizmetlerimizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DijitalCozumlerRoute: DijitalCozumlerRoute,
  GlobalAgRoute: GlobalAgRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  HizmetlerimizRoute: HizmetlerimizRoute,
  IletisimRoute: IletisimRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
